twelve

diff --git a/.github/workflows/publish-on-release.yml b/.github/workflows/publish-on-release.yml
--- a/.github/workflows/publish-on-release.yml
+++ b/.github/workflows/publish-on-release.yml
@@ -9,29 +9,29 @@ jobs:
     name: Build
     runs-on: ubuntu-latest
     outputs:
-      VERSION: ${{ steps.ver.outputs.version }}
+      VERSION: ${{ steps.check.outputs.version }}
+    permissions:
+      contents: write
     steps:
       - uses: actions/checkout@v4
       - name: Setup Build
         uses: ./.github/actions/build_setup
-      - name: Version Check
+      - name: Check Tag with Version
         id: check
         run: |
-          VER=$(./gradlew -q printVersion | awk -F- '{print "v"$2}')
-          if [[ "$VER" = ${{ github.event.release.tag_name }} ]]; then exit 0; else exit 1; fi
+          VER=$(./gradlew -q printVersion)
+          echo "version=$VER" >> $GITHUB_OUTPUT
+          TAG=$(echo $VER | awk -F- '{print "v"$2}')
+          if [[ "$TAG" = ${{ github.event.release.tag_name }} ]]; then exit 0; else exit 1; fi
       - name: Build
         run: ./gradlew assemble --build-cache
-      - name: Get Version from Gradle
-        id: ver
-        run: echo "version=$(./gradlew -q printVersion)" >> $GITHUB_OUTPUT
-      - name: Upload Artifact
+      - name: Upload Build Artifacts
         uses: actions/upload-artifact@v4
         with:
           name: build-artifacts
           path: build/libs/*
           if-no-files-found: error
           retention-days: 3
-
 
   upload-release-artifacts:
     name: Upload Release Artifacts
@@ -53,25 +53,36 @@ jobs:
           files: ./!(*-@(dev|dev-all|dev-slim|javadoc)).jar
           fail_on_unmatched_files: true
 
-  publish:
-    name: Publish to Maven, CF, Modrinth
-    needs: [build, upload-release-artifacts]
+  publish-maven:
+    name: Publish to GTCEU Maven
+    needs: build
+    if: github.event.release.name != 'simulate'
     runs-on: ubuntu-latest
     env:
       MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
       MAVEN_USER: ${{ secrets.MAVEN_USER }}
     permissions:
       contents: write
-      pull-requests: write
     steps:
       - uses: actions/checkout@v4
+      - name: Setup Build
+        uses: ./.github/actions/build_setup
+      - name: Publish
+        run: ./gradlew publish --build-cache
+
+  publish-cf-modrinth:
+    name: Publish to CF and Modrinth
+    needs: build
+    if: github.event.release.name != 'simulate'
+    runs-on: ubuntu-latest
+    permissions:
+      contents: write
+    steps:
       - name: Download artifacts
         uses: actions/download-artifact@v4
         with:
           name: build-artifacts
-
       - name: Publish Mod
-        if: github.event.release.name != 'simulate'
         uses: Kir-Antipov/mc-publish@v3.3.0
         with:
           modrinth-id: 7tG215v7
@@ -90,11 +101,20 @@ jobs:
           java: 17
           fail-mode: fail
 
-      # After release, PR ver bump to gradle.properties
+  # After successful release, PR ver bump to gradle.properties
+  bump-version:
+    name: Bump Version
+    needs: [ build, upload-release-artifacts, publish-maven, publish-cf-modrinth ]
+    if: ${{ always() && !failure() && !cancelled() }}
+    runs-on: ubuntu-latest
+    permissions:
+      contents: write
+      pull-requests: write
+    env:
+      GH_TOKEN: ${{ github.token }}
+    steps:
+      - uses: actions/checkout@v4
       - name: Bump Version
-        if: ${{ success() }}
-        env:
-          GH_TOKEN: ${{ github.token }}
         run: |
           git config user.name 'github-actions[bot]'
           git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
@@ -107,10 +127,15 @@ jobs:
           git push --force --set-upstream origin gh/ver-bump
           gh pr create -B $MC_VER -H gh/ver-bump --title "Bump version to $BUMPED" --body "Created by GH Workflow"
 
-      # Change release to draft if something failed above
-      - name: Edit Failed Release
-        if: ${{ failure() }}
-        env:
-          GH_TOKEN: ${{ github.token }}
-        run: |
-          gh release edit ${{ github.event.release.tag_name }} --draft=true
+  # Change release to draft if something failed above
+  fail-release:
+    name: Edit Failed Release
+    needs: [ build, upload-release-artifacts, publish-maven, publish-cf-modrinth ]
+    if: ${{ always() && (failure() || cancelled()) }}
+    runs-on: ubuntu-latest
+    permissions:
+      contents: write
+    env:
+      GH_TOKEN: ${{ github.token }}
+    steps:
+        - run: gh release edit ${{ github.event.release.tag_name }} --draft=true
